import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  const products = [
    {
      name: 'Silk Slip Midi Dress',
      brand: 'Reformation',
      description: 'A fluid slip dress finished in a silk blend with a subtle sheen and softly draped silhouette.',
      price: 178.0,
      originalPrice: 245.0,
      discount: 27,
      category: 'Dresses',
      images: [
        'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Ivory', hex: '#f5efe7' }, { name: 'Midnight', hex: '#1c1a18' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['minimalist', 'evening', 'silk'],
      stock: 12,
      rating: 4.8,
      reviewCount: 218,
      isNew: true,
    },
    {
      name: 'Oversized Wool Blend Coat',
      brand: 'COS',
      description: 'A modern oversized coat in a wool blend with a relaxed shoulder and structured collar.',
      price: 420.0,
      originalPrice: 520.0,
      discount: 19,
      category: 'Outerwear',
      images: [
        'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Camel', hex: '#b89978' }, { name: 'Charcoal', hex: '#2f2d2a' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['luxury', 'tailored', 'outerwear'],
      stock: 8,
      rating: 4.7,
      reviewCount: 84,
      isNew: true,
    },
    {
      name: 'Leather Track Runner',
      brand: 'Nike',
      description: 'A minimalist runner in premium leather with a sleek profile and cushioned sole.',
      price: 145.0,
      category: 'Shoes',
      images: [
        'https://images.unsplash.com/photo-1519741495232-6b3f5de3c1c9?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'White', hex: '#fbf8f1' }, { name: 'Black', hex: '#100f0d' }],
      sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
      tags: ['streetwear', 'sneaker', 'minimalist'],
      stock: 30,
      rating: 4.5,
      reviewCount: 134,
    },
    {
      name: 'Textured Cotton Poplin Shirt',
      brand: 'Mango',
      description: 'A crisp poplin shirt with architectural lines and an oversized silhouette.',
      price: 78.0,
      category: 'Tops',
      images: [
        'https://images.unsplash.com/photo-1495121605193-b116b5b9c5d0?auto=format&fit=crop&w=900&q=80',
        'https://images.unsplash.com/photo-1423784346385-c1d4dac9893a?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Cream', hex: '#ece5d8' }, { name: 'Black', hex: '#1d1b17' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['daywear', 'office', 'minimalist'],
      stock: 20,
      rating: 4.3,
      reviewCount: 67,
    },
    {
      name: 'High-Rise Raw Denim Jean',
      brand: 'A.P.C.',
      description: 'A clean high-rise jean in raw denim with a sculpted waist and straight leg.',
      price: 168.0,
      category: 'Bottoms',
      images: [
        'https://images.unsplash.com/photo-1472417583565-62e7bdeda490?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Indigo', hex: '#283f6c' }, { name: 'Black', hex: '#1d1b17' }],
      sizes: ['26', '27', '28', '29', '30', '31', '32', '33'],
      tags: ['denim', 'casual', 'heritage'],
      stock: 22,
      rating: 4.4,
      reviewCount: 109,
    },
    {
      name: 'Suede Ankle Boot',
      brand: 'Saint Laurent',
      description: 'A tonal suede ankle boot with sculpted heel and minimal hardware.',
      price: 690.0,
      originalPrice: 790.0,
      discount: 13,
      category: 'Shoes',
      images: [
        'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Chocolate', hex: '#38291f' }],
      sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
      tags: ['luxury', 'evening', 'leather'],
      stock: 10,
      rating: 4.7,
      reviewCount: 58,
      isNew: true,
    },
    {
      name: 'Gold-Plated Hoop Earrings',
      brand: 'Mejuri',
      description: 'Polished gold-plated hoops with a delicate weight for everyday elegance.',
      price: 89.0,
      category: 'Accessories',
      images: [
        'https://images.unsplash.com/photo-1530446763277-81f5878f1d7f?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Gold', hex: '#c9a96e' }],
      sizes: ['One Size'],
      tags: ['jewelry', 'minimalist', 'everyday'],
      stock: 34,
      rating: 4.9,
      reviewCount: 142,
    },
    {
      name: 'Sculpted Knit Sheath Dress',
      brand: 'The Row',
      description: 'A refined knit sheath dress finished with a clean neckline and fluid drape.',
      price: 1290.0,
      category: 'Dresses',
      images: [
        'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Ivory', hex: '#eee4da' }, { name: 'Black', hex: '#131210' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['luxury', 'workwear', 'minimalist'],
      stock: 6,
      rating: 4.9,
      reviewCount: 39,
    },
    {
      name: 'Rain-Ready Trench Coat',
      brand: 'Burberry',
      description: 'A classic water-resistant trench updated with polished hardware and precise tailoring.',
      price: 1250.0,
      originalPrice: 1450.0,
      discount: 14,
      category: 'Outerwear',
      images: [
        'https://images.unsplash.com/photo-1533112784649-8f45d7b3355a?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Stone', hex: '#c9bea9' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['investment', 'timeless', 'weatherproof'],
      stock: 5,
      rating: 4.6,
      reviewCount: 88,
    },
    {
      name: 'Logo Canvas Tote',
      brand: 'Balenciaga',
      description: 'A contemporary canvas tote with tonal logo details and a soft structured handle.',
      price: 640.0,
      category: 'Accessories',
      images: [
        'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Cream', hex: '#efe7d9' }, { name: 'Black', hex: '#1b1815' }],
      sizes: ['One Size'],
      tags: ['luxury', 'everyday', 'cargo'],
      stock: 14,
      rating: 4.4,
      reviewCount: 51,
    },
    {
      name: 'Fine Merino Crewneck Sweater',
      brand: 'Arket',
      description: 'A lightweight merino crewneck that layers seamlessly and elevates everyday dressing.',
      price: 115.0,
      category: 'Tops',
      images: [
        'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'Flint', hex: '#4a4a48' }, { name: 'Sand', hex: '#d7cabd' }],
      sizes: ['XS', 'S', 'M', 'L', 'XL'],
      tags: ['knitwear', 'layering', 'minimalist'],
      stock: 28,
      rating: 4.5,
      reviewCount: 73,
    },
    {
      name: 'Court Leather Sneaker',
      brand: 'Adidas',
      description: 'A premium leather sneaker with a refined court silhouette and cushioned sole.',
      price: 110.0,
      category: 'Shoes',
      images: [
        'https://images.unsplash.com/photo-1519741495232-6b3f5de3c1c9?auto=format&fit=crop&w=900&q=80',
      ],
      colors: [{ name: 'White', hex: '#fbf7f1' }, { name: 'Navy', hex: '#2c3a56' }],
      sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11', '11.5', '12'],
      tags: ['casual', 'sporty', 'streetwear'],
      stock: 26,
      rating: 4.3,
      reviewCount: 93,
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product as any });
  }
  console.log('Seeded', products.length, 'products');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
